services:
  network-deploy-service:
    networks:
      - learnspring

  microservice-base-config:
    extends:
      service: network-deploy-service
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 700M
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq

  microservice-configserver-config:
    extends:
      service: microservice-base-config
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/