services:
  accountsdb:
    image: mysql
    container_name: accountsdb
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: accountsdb
    extends:
      service: microservice-db-config
      file: common-config.yml

  loansdb:
    image: mysql
    container_name: loansdb
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: loansdb
    extends:
      service: microservice-db-config
      file: common-config.yml

  cardsdb:
    image: mysql
    container_name: cardsdb
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: cardsdb
    extends:
      service: microservice-db-config
      file: common-config.yml

  configserver:
    build:
      context: ../../configserver
      dockerfile: Dockerfile
    container_name: configserver
    ports:
      - "8071:8071"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8071/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    extends:
      file: common-config.yml
      service: microservice-base-config

  accounts:
    build:
      context: ../../accounts
      dockerfile: Dockerfile
    container_name: accounts
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: "accounts"
      SPRING_DATASOURCE_URL: jdbc:mysql://accountsdb:3306/accountsdb
    depends_on:
      - accountsdb
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  loans:
    build:
      context: ../../loans
      dockerfile: Dockerfile
    container_name: loans
    ports:
      - "8090:8090"
    environment:
      SPRING_APPLICATION_NAME: "loans"
      SPRING_DATASOURCE_URL: jdbc:mysql://loansdb:3306/loansdb
    depends_on:
      - loansdb
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  cards:
    build:
      context: ../../cards
      dockerfile: Dockerfile
    container_name: cards
    ports:
      - "9000:9000"
    environment:
      SPRING_APPLICATION_NAME: "cards"
      SPRING_DATASOURCE_URL: jdbc:mysql://cardsdb:3306/cardsdb
    depends_on:
      - cardsdb
    extends:
      file: common-config.yml
      service: microservice-configserver-config

networks:
  learnspring:
    driver: bridge